=== Informatievlaanderen/OSLOthema-zaalreservatie/schemas/configuration.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/Configuration",
  "definitions": {
    "Configuration": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "category": {
          "type": "string"
        },
        "usage": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "responsibleOrganisation": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "resourceReference": {
                "type": "string"
              }
            },
            "additionalProperties": false
          }
        },
        "publicationDate": {
          "type": "string"
        },
        "descriptionFileName": {
          "type": "string"
        },
        "specificationDocuments": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "resourceReference": {
                "type": "string"
              }
            },
            "additionalProperties": false
          }
        },
        "documentation": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "resourceReference": {
                "type": "string"
              }
            },
            "additionalProperties": false
          }
        },
        "charter": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "resourceReference": {
              "type": "string"
            }
          },
          "additionalProperties": false
        },
        "reports": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "resourceReference": {
                "type": "string"
              }
            },
            "additionalProperties": false
          }
        },
        "presentations": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "resourceReference": {
                "type": "string"
              }
            },
            "additionalProperties": false
          }
        },
        "dateOfRegistration": {
          "type": "string"
        },
        "dateOfAcknowledgementByWorkingGroup": {
          "type": "string"
        },
        "dateOfAcknowledgementBySteeringCommittee": {
          "type": "string"
        },
        "datePublicReviewStart": {
          "type": "string"
        },
        "datePublicReviewEnd": {
          "type": "string"
        },
        "endOfPublicationDate": {
          "type": "string"
        }
      },
      "required": [
        "title",
        "category",
        "usage",
        "status",
        "responsibleOrganisation",
        "publicationDate",
        "descriptionFileName",
        "specificationDocuments",
        "documentation",
        "charter",
        "reports",
        "presentations",
        "dateOfRegistration",
        "dateOfAcknowledgementByWorkingGroup",
        "dateOfAcknowledgementBySteeringCommittee",
        "datePublicReviewStart",
        "datePublicReviewEnd",
        "endOfPublicationDate"
      ],
      "additionalProperties": false
    }
  }
}

=== Informatievlaanderen/OSLOthema-zaalreservatie/ap-zaalreservatie-config.json
{
  "title": "Applicatieprofiel Zaalreservatie",
  "category": "Applicatieprofiel",
  "usage": "Aanbevolen (vrijwillig)",
  "status": "Standaard-in-ontwikkeling",
  "responsibleOrganisation": [
    {
      "name": "Agentschap Digitaal Vlaanderen",
      "resourceReference": "https://data.vlaanderen.be/id/organisatie/OVO002949"
    }
  ],
  "publicationDate": "2025-04-17",
  "descriptionFileName": "zaalreservatie-description.md",
  "specificationDocuments": [
    {
      "name": "Applicatieprofiel Zaalreservatie",
      "resourceReference": "https://data.vlaanderen.be/doc/applicatieprofiel/zaalreservatie/"
    }
  ],
  "documentation": 
  [
   {
      "name": "Vocabularium Zaalreservatie",
      "resourceReference": "https://data.vlaanderen.be/ns/zaalreservatie/"
    } 
  ],
  "charter": 
  {
    "name": "Charter Zaalreservatie",
    "resourceReference": "https://github.com/Informatievlaanderen/OSLOthema-zaalreservatie/blob/standaardenregister/charter/Charter%20Zaalreservatie.pdf"
  },
  "reports":
  [
    {
      "name": "Verslag Business Werkgroep - 14 januari 2025",
      "resourceReference": "https://github.com/Informatievlaanderen/OSLOthema-zaalreservatie/blob/standaardenregister/reports/Verslag%20BW%20OSLO%20Zaalreservatie.pdf"
    },
    {
      "name": "Verslag Thematische Werkgroep I - 18 februari 2025",
      "resourceReference": "https://github.com/Informatievlaanderen/OSLOthema-zaalreservatie/blob/standaardenregister/reports/Verslag%20TW1%20OSLO%20Zaalreservatie.pdf"
    },
    {
      "name": "Verslag Thematische Werkgroep II - 18 maart 2025",
      "resourceReference": "https://github.com/Informatievlaanderen/OSLOthema-zaalreservatie/blob/standaardenregister/reports/Verslag%20TW2%20OSLO%20Zaalreservatie.pdf"
    }
  ],
  "presentations": [
   {
      "name": "Presentatie Business Werkgroep -  14 januari 2025",
      "resourceReference": "https://github.com/Informatievlaanderen/OSLOthema-zaalreservatie/blob/standaardenregister/presentations/Business%20Werkgroep%20Zaalreservatie.pdf"
    },
    {
      "name": "Presentatie Thematische Werkgroep I - 18 februari 2025",
      "resourceReference": "https://github.com/Informatievlaanderen/OSLOthema-zaalreservatie/blob/standaardenregister/presentations/Thematische%20werkgroep%201%20OSLO%20Zaalreservatie.pdf"
    },
    {
      "name": "Presentatie Thematische Werkgroep II - 18 maart 2025",
      "resourceReference": "https://github.com/Informatievlaanderen/OSLOthema-zaalreservatie/blob/standaardenregister/presentations/Thematische%20werkgroep%202%20OSLO%20Zaalreservatie.pdf"
    }
    ],
  "dateOfRegistration": "2025-01-09",
  "dateOfAcknowledgementByWorkingGroup": "TBD",
  "dateOfAcknowledgementBySteeringCommittee": "TBD",
  "datePublicReviewStart": "TBD",
  "datePublicReviewEnd": "TBD",
  "endOfPublicationDate": ""
}

=== Informatievlaanderen/OSLOthema-zaalreservatie/ap-or-voc-config.json
{
  "title": "Applicatieprofiel Zaalreservatie",
  "category": "Applicatieprofiel",
  "usage": "Aanbevolen (vrijwillig)",
  "status": "Standaard in ontwikkeling",
  "responsibleOrganisation": [
    {
      "name": "Agentschap Digitaal Vlaanderen",
      "resourceReference": "https://data.vlaanderen.be/id/organisatie/OVO002949"
    }
  ],
  "publicationDate": "2025-04-17",
  "descriptionFileName": "",
  "specificationDocuments": [],
  "documentation": [],
  "charter": {},
  "reports": [],
  "presentations": [],
  "dateOfRegistration": "2025-01-09",
  "dateOfAcknowledgementByWorkingGroup": "TBD",
  "dateOfAcknowledgementBySteeringCommittee": "TBD",
  "datePublicReviewStart": "TBD",
  "datePublicReviewEnd": "TBD",
  "endOfPublicationDate": ""
}
